---
title: "new_analses"
author: "Maxwel Coura Oliveira"
date: "6/7/2021"
output: html_document
---


```{r}
library(tidyverse)
library(lubridate)
library(drc)
library(broom)
library(tidytext)
library(ggthemes)
library(ggtext)
library(patchwork)
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Roboto", "roboto") 
```







```{r}
data <- read_csv("data2.csv")
```


```{r}
data %>% 
  filter(location != "grant") %>% 
  mutate(location = str_replace(location, "havelock", "lincon"))-> data1
```

```{r}
data1 %>% 
  rename(month = planting,
         planting = planting_1) %>% 
  mutate(planting = mdy(planting),
         harvest = mdy(harvest),
         doyp = yday(planting)) %>% 
  mutate_if(is_character, as_factor) -> data2
```


```{r}
data2 %>% 
  mutate(harvest = as.character(harvest)) %>% 
  mutate(harvest = str_replace(harvest, "2018", "2019"),
         harvest = ymd(harvest)) %>% 
  filter(!is.na(harvest)) %>% 
  dplyr::select(location, month, crop, harvest) %>% 
  group_by(location, month, crop) %>% 
  count(harvest, name = "harvest_day") -> harvest
```


```{r}
data2 %>% 
  filter(!is.na(harvest)) %>% 
  dplyr::select(location, month, crop, harvest) %>% 
  group_by(location, month, crop) %>% 
  count(location, month, crop, name = "total") -> total
```


```{r}
total %>% 
  left_join(harvest) %>% 
  mutate(prop = harvest_day / total) %>% 
  mutate(lag = lag(prop)) %>% 
  mutate(prob = cumsum(prop)) -> cum_sum
```



```{r}
data2 %>% 
  mutate(harvest = str_replace(harvest, "2018", "2019"),
         harvest = ymd(harvest)) %>% 
  filter(!is.na(harvest)) %>% 
  left_join(cum_sum) %>% 
  rename(harvest_com = harvest) %>% 
  dplyr::select(-lag) -> data3
```


```{r}
data3 %>% 
  ggplot(aes(x = dap, y = prob, color = crop)) +
  geom_point() +
  facet_grid(location ~ month)
```
```{r}
car::leveneTest(prob ~ location, data = data3)
```

```{r}
data3 %>% 
  unite("trt", c("location", "crop"), sep = "-") -> data4
```


# June

```{r}
june <-  data4 %>% 
  filter(month == "June")
model <- drm(prob*100 ~ doyh, trt, fct = W2.3(fixed = c(NA, 100, NA)), data = june)

plot(model, col = c(1,2,3), type = "average", ylab = "Cumulative flowering (%)",
     xlab = "Day of the year")
```
```{r}
#broom::tidy(model_arl)
summary(model)
```

```{r}
ed_values <- ED(model, c(10, 50, 90), interval = "delta", type = "absolute")
```

```{r}
ed_values %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("location", "crop"), sep = "-") %>% 
  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed_values1
```


```{r}
label1 <- tibble(ed = "50% flowering", crop = "corn", 
                   x = 3.5, y = 185, label = "Transplanting \nday")
rect1 <- tibble(ed = "50% flowering", crop = "corn", 
               x = 3.5, y = 153, xend = 3.5, yend = 165)
```


```{r}
month <- tibble(ed = "90% flowering",
                crop = "corn",
                x = c(0.65, 0.65, 0.65, 0.65),
                y = c(168, 197, 228.5, 259), 
                label = c("June", "July", "August", "September"))


ed_values1 %>% 
  filter(crop == "corn") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>% 
  ggplot(aes(x = location, y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 153, ymax= 183), 
            fill = "#FFFDD0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 153, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2, color = c("#8B8000", "#80461b", 
                                  "darkgreen", "blue")) +
  labs(y = NULL, x = NULL,
       title = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  geom_curve(data = rect1, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3) + 
  geom_text(data = label1, 
            aes(x = x, y = y), 
            size = 2,
            label = label1$label, color = "red") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(),
        strip.text = element_markdown(face = "bold"),
        plot.title.position = "plot") -> p1c
```


```{r}
month <- tibble(ed = "90% flowering",
                crop = "fallow",
                x = c(0.65, 0.65, 0.65, 0.65),
                y = c(168, 197, 228.5, 259), 
                label = c("June", "July", "August", "September"))



ed_values1 %>% 
  filter(crop == "fallow") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>% 
  ggplot(aes(x = location, y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 153, ymax= 183), 
            fill = "#FFFDD0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 153, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2, color = c("#8B8000", "#80461b", 
                                  "darkgreen", "blue")) +
  labs(y = "Day of year", x = NULL,
       title = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(),
        strip.text = element_markdown(face = "bold"),
        plot.title.position = "plot") -> p1f
```


```{r}
month <- tibble(ed = "90% flowering",
                crop = "corn",
                x = c(0.65, 0.65, 0.65, 0.65),
                y = c(168, 197, 228.5, 259), 
                label = c("June", "July", "August", "September"))


ed_values1 %>% 
  filter(crop == "corn") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>% 
  ggplot(aes(x = location, y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 153, ymax= 183), 
            fill = "#FFFDD0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 153, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2, color = c("#8B8000", "#80461b", 
                                  "darkgreen", "blue")) +
  labs(y = NULL, x = NULL,
       title = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(),
        strip.text = element_markdown(face = "bold"),
        plot.title.position = "plot") -> p1s
```


```{r}
library(patchwork)
f1 <- p1c | p1f | p1s +
  plot_annotation(
  title = "DOY of 10, 50, and 90% Palmer amaranth flowering after first transplanting") 
  ggsave("figures/June.png", width = 9, height = 5, dpi = 600, f1)
```







# July

```{r}
july <-  data4 %>% 
  filter(month == "July")
model2 <- drm(prob*100 ~ doyh, trt, fct = W2.3(fixed = c(NA, 100, NA)), data = july)

plot(model2, col = c(1,2,3), type = "average", ylab = "Cumulative flowering (%)",
     xlab = "Day of the year")
```

```{r}
#broom::tidy(model_arl)
summary(model2)
```

```{r}
ed_values2 <- ED(model2, c(10, 50, 90), interval = "delta", type = "absolute")
```

```{r}
ed_values2 %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("location", "crop"), sep = "-") %>% 
  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed_values3
```


```{r}
label2 <- tibble(ed = "50% flowering", crop = "corn", 
                   x = 3.5, y = 211, label = "Transplanting \nday")
rect2 <- tibble(ed = "50% flowering", crop = "corn", 
               x = 3.5, y = 183, xend = 3.5, yend = 195)
```

```{r}
month <- tibble(ed = "90% flowering",
                crop = "corn",
                x = c( 0.65, 0.65, 0.65),
                y = c(197, 228.5, 259), 
                label = c("July", "August", "September"))
```

```{r}
ed_values3 %>% 
  filter(crop == "corn") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>%
  ggplot(aes(x = location,
             y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 183, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2.5, color = c("#80461b", "darkgreen", "blue")) +
  labs(y = NULL, x = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  geom_curve(data = rect2, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3) + 
  geom_text(data = label2, 
            aes(x = x, y = y), 
            size = 2,
            label = label2$label, color = "red") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold"),
        plot.title = element_markdown(),
        plot.title.position = "plot") -> p2c
```

```{r}
month <- tibble(ed = "90% flowering",
                crop = "fallow",
                x = c( 0.65, 0.65, 0.65),
                y = c(197, 228.5, 259), 
                label = c("July", "August", "September"))
```


```{r}
ed_values3 %>% 
  filter(crop == "fallow") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>%
  ggplot(aes(x = location,
             y = estimate)) +
    scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 183, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2.5, color = c("#80461b", "darkgreen", "blue")) +
  labs(y = "Day of year", x = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold"),
        plot.title = element_markdown(),
        plot.title.position = "plot") -> p2f
```

```{r}
month <- tibble(ed = "90% flowering",
                crop = "soybean",
                x = c( 0.65, 0.65, 0.65),
                y = c(197, 228.5, 259), 
                label = c("July", "August", "September"))


ed_values3 %>% 
  filter(crop == "soybean") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(crop,  ed) %>% 
  mutate(location = reorder_within(location, 
                                   by = estimate, 
                                   within = ed)) %>%
  ggplot(aes(x = location,
             y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 4.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 183, size = 1.1, 
             color = "red",
             alpha = 1) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.2) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2.5, color = c("#80461b", "darkgreen", "blue")) +
  labs(y = NULL, x = NULL) +
  facet_grid(ed ~ crop, scales = "free_y") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold"),
        plot.title = element_markdown(),
        plot.title.position = "plot") -> p2s
p2s
```


```{r}
library(patchwork)
f3 <- p2c | p2f | p2s +
  plot_annotation(
  title = "DOY of 10, 50, and 90% Palmer amaranth flowering after second transplanting") 
  ggsave("figures/July.png", width = 9, height = 5, dpi = 600, f3)
```





#### -----

```{r}
library(ggdist)
library(PupillometryR)
```

# Biomass

```{r}
data <- read_csv("data2.csv")
```


```{r}
data %>% 
  rename(month = planting,
         planting = planting_1) %>% 
  mutate(planting = mdy(planting),
         harvest = mdy(harvest),
         doyp = yday(planting)) %>% 
  mutate_if(is_character, as_factor) -> data1
```

```{r}
data1 %>% 
  mutate(month = fct_recode(month,
                            "first planting" = "June",
                            "second planting" = "July")) -> data1
```



```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "corn") %>% 
  filter(!is.na(weight)) %>% 
  ggplot(aes(x = fct_reorder(location, weight), y = weight,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg1
```


```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "fallow") %>% 
  filter(!is.na(weight)) %>% 
  ggplot(aes(x = fct_reorder(location, weight), y = weight,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = "Biomass (g)") +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg2
```


```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "soybean") %>% 
  filter(!is.na(weight)) %>% 
  ggplot(aes(x = fct_reorder(location, weight), y = weight,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg3
```

```{r}
f4 <- fg1 | fg2 | fg3 +
  plot_annotation(
  title = NULL) 
  ggsave("figures/biomass.png", width = 9, height = 5, dpi = 600, f4)
```


# Height


```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "corn") %>% 
  filter(!is.na(height)) %>% 
  ggplot(aes(x = fct_reorder(location, height), y = height,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg4
```


```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "fallow") %>% 
  filter(!is.na(height)) %>% 
  ggplot(aes(x = fct_reorder(location, height), y = height,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = "Height (cm)") +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg5
```


```{r}
data1 %>% 
  mutate(location = str_to_title(location)) %>% 
  filter(crop == "soybean") %>% 
  filter(!is.na(height)) %>% 
  ggplot(aes(x = fct_reorder(location, height), y = height,
             color = location, 
             fill = location)) + 
  geom_jitter(position = position_nudge(x = -0.2, y = 0), alpha = 0.1) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   stat = "ydensity",
                   alpha = 0.8, scale = "count") +
  stat_summary(fun = "mean", colour = "red", size = 1, geom = "point") +
  scale_color_viridis_d(option = "H") + 
  scale_fill_viridis_d(option = "H") + 
  theme_test() +
  facet_grid(month ~ crop, scales = "free") +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold")) -> fg6
```

```{r}
f5 <- fg4 | fg5 | fg6 +
  plot_annotation(
  title = NULL) 
  ggsave("figures/height.png", width = 9, height = 5, dpi = 300, f5)
```





###--------------------------

```{r}
data %>% 
  filter(location != "grant") %>% 
  mutate(location = str_replace(location, "havelock", "lincon"))-> data1
```

```{r}
data1 %>% 
  rename(month = planting,
         planting = planting_1) %>% 
  mutate(planting = mdy(planting),
         harvest = mdy(harvest),
         doyp = yday(planting)) %>% 
  mutate_if(is_character, as_factor) -> data2
```


```{r}
data2 %>% 
  mutate(harvest = as.character(harvest)) %>% 
  mutate(harvest = str_replace(harvest, "2018", "2019"),
         harvest = ymd(harvest)) %>% 
  filter(!is.na(harvest)) %>% 
  dplyr::select(location, month, crop, harvest) %>% 
  group_by(month, crop) %>% 
  count(harvest, name = "harvest_day") -> harvest
```


```{r}
data2 %>% 
  filter(!is.na(harvest)) %>% 
  dplyr::select(location, month, crop, harvest) %>% 
  group_by(month, crop) %>% 
  count(month, crop, name = "total") -> total
```

```{r}
total %>% 
  left_join(harvest) %>% 
  mutate(prop = harvest_day / total) %>% 
  mutate(lag = lag(prop)) %>% 
  mutate(prob = cumsum(prop)) %>% 
  mutate(doyh = yday(harvest)) -> cum_sum
```



```{r}
data2 %>% 
  mutate(harvest = str_replace(harvest, "2018", "2019"),
         harvest = ymd(harvest)) %>% 
  filter(!is.na(harvest)) %>% 
  ungroup() %>% 
  left_join(cum_sum) %>% 
  rename(harvest_com = harvest) %>% 
  dplyr::select(-lag) -> data3
```

# June

```{r}
data3 %>% 
  filter(month == "June") -> month_jun 
model3 <- drm(prob*100 ~ doyh, crop, fct = W1.3(), data = month_jun)

plot(model3, col = c(1,2,3), type = "average", ylab = "Cumulative flowering (%)",
     xlab = "Day of the year")
```


```{r}
#broom::tidy(model_arl)
summary(model3)
```

```{r}
ed_values3 <- ED(model3, c(10, 50, 90), interval = "delta", type = "absolute")
```

```{r}
ed_values3 %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "crop", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed_values3
```


```{r}
label1 <- tibble(ed = "90% flowering", 
                   x = 2.5, y = 185, label = "Transplanting \nday")
rect1 <- tibble(ed = "90% flowering", 
               x = 2.5, y = 153, xend = 2.5, yend = 165)
```


```{r}
month <- tibble(ed = "90% flowering",
                x = c(0.65, 0.65, 0.65, 0.65),
                y = c(168, 197, 228.5, 259), 
                label = c("June", "July", "August", "September"))
```


```{r}
ed_values3 %>% 
  mutate(month = "First transplanting") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(month,  ed) %>% 
  mutate(crop = reorder_within(crop, 
                                   by = estimate, 
                                   within = ed)) %>% 
  ggplot(aes(x = crop, y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 153, ymax= 183), 
            fill = "#FFFDD0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 153, size = 1.1, 
             color = "#CCCC00",
             alpha = 1) +
  geom_point(size = 2, aes(color = crop, 
                           shape = crop)) +
  geom_linerange(aes(ymin = lower, ymax = upper, color = crop, 
                     shape = crop), size = 1.3) +
  scale_color_manual(values = c("#412234","#EE4B2B","#32CD32",
                                "#412234","#EE4B2B","#32CD32",
                                "#412234","#EE4B2B","#32CD32")) +
  scale_shape_manual(values = c(15,16,17,15,16,17,15,16,17)) +
  facet_grid(ed ~ month, scales = "free_y") +
  coord_flip() +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2, color = c("#8B8000", "#80461b", 
                                  "darkgreen", "blue")) +
  labs(y = NULL, x = NULL,
       title = NULL) +
  geom_curve(data = rect1, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3) + 
  geom_text(data = label1, 
            aes(x = x, y = y), 
            size = 2,
            label = label1$label, color = "#CCCC00") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(),
        strip.text = element_markdown(face = "bold"),
        plot.title.position = "plot") -> p1c
p1c
```



# July

```{r}
data3 %>% 
  filter(month == "July") -> month_jul 
model4 <- drm(prob*100 ~ doyh, crop, fct = W1.3(), data = month_jul)

plot(model4, col = c(1,2,3), type = "average", ylab = "Cumulative flowering (%)",
     xlab = "Day of the year")
```


```{r}
#broom::tidy(model_arl)
summary(model4)
```

```{r}
ed_values4 <- ED(model4, c(10, 50, 90), interval = "delta", type = "absolute")
```

```{r}
ed_values4 %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "crop", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed_values4
```


```{r}
label2 <- tibble(ed = "90% flowering", 
                   x = 2.5, y = 211, label = "Transplanting \nday")
rect2 <- tibble(ed = "90% flowering",  
               x = 2.5, y = 183, xend = 2.5, yend = 195)
```

```{r}
month1 <- tibble(ed = "90% flowering",
                x = c(0.65, 0.65, 0.65),
                y = c(197, 228.5, 259), 
                label = c("July", "August", "September"))
```


```{r}
ed_values4 %>% 
  mutate(month = "Second transplanting") %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  group_by(month,  ed) %>% 
  mutate(crop = reorder_within(crop, 
                                   by = estimate, 
                                   within = ed)) %>% 
  ggplot(aes(x = crop, y = estimate)) +
  scale_x_reordered(expand = c(.01, .01)) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 183, ymax= 214), 
            fill = "#80461b", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 214, ymax= 244), 
            fill = "lightgreen", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.5, xmax= 3.5,
                        ymin= 244, ymax= 274), 
            fill = "blue", alpha=0.05) +
  geom_hline(yintercept = 183, size = 1.1, 
             color = "#D2691E",
             alpha = 1) +
  geom_point(size = 2, aes(color = crop, shape = crop)) +
  geom_linerange(aes(ymin = lower, ymax = upper, color = crop), size = 1.3) +
  scale_color_manual(values = c("#412234","#EE4B2B","#32CD32",
                                "#412234","#EE4B2B","#32CD32",
                                "#412234","#32CD32","#EE4B2B")) +
  scale_shape_manual(values = c(15,16,17,15,16,17,15,17,16)) +
  geom_text(data = month1, aes(x = x, y = y), label = month1$label,
            size = 2, color = c("#80461b", "darkgreen", "blue")) +
  labs(y = NULL, x = NULL) +
  facet_grid(ed ~ month, scales = "free_y") +
  geom_curve(data = rect2, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3) + 
  geom_text(data = label2, 
            aes(x = x, y = y), 
            size = 2,
            label = label2$label, color = "#D2691E") +
  coord_flip() +
  theme_test() +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold"),
        plot.title = element_markdown(),
        plot.title.position = "plot") -> p2c
```


```{r}
library(patchwork)
f3 <- p1c | p2c +
  plot_annotation(
  title = "DOY of 10, 50, and 90% Palmer amaranth flowering") 
  ggsave("figures/Combined.png", width = 6, height = 5, dpi = 600, f3)
```




# Biomass

```{r}
data <- read_csv("data2.csv")
```


```{r}
data %>% 
  rename(month = planting,
         planting = planting_1) %>% 
  mutate(planting = mdy(planting),
         harvest = mdy(harvest),
         doyp = yday(planting)) -> data1
```

```{r}
data1 %>% 
  mutate(month = fct_recode(month,
                            "First transplanting" = "June",
                            "Second transplanting" = "July")) -> data1
```
```{r}
data1 %>% 
  filter(!is.na(weight)) %>% 
  group_by(year, location, month, crop) %>% 
  mutate(n = n()) %>% 
  mutate(biomass = weight / n) -> biom
```
```{r}
biom %>% 
  ggplot(aes(x = log(biomass))) + 
  geom_histogram()
```

```{r}
library(lme4)
library(lmerTest)
library(emmeans)
```

```{r}
biom %>%
  group_by(month) %>% 
  nest(-month) %>% 
  mutate(model = map(data, ~ lmer(log(biomass) ~ crop * location + 
                                 (1|year), data = .x)),
         anova = map(model, anova),
         emmeans = map(model, ~ emmeans(., ~ location | crop, 
                                        type = "response"))) -> analysis
```

```{r}
#anova
analysis$anova[[2]]
```

```{r}
analysis$emmeans[[2]] %>% 
  as_tibble() %>% 
  mutate(month = "Second transplanting") -> second

analysis$emmeans[[1]] %>% 
  as_tibble() %>% 
  mutate(month = "First transplanting") %>% 
  bind_rows(second) %>% 
  mutate(location = str_to_title(location)) %>% 
  mutate(location = fct_recode(location,
                              "Lincoln" = "Havelock")) -> result
```


```{r}
theme_set(theme_test(base_family = "roboto"))
result %>% 
  ggplot(aes(x = location, y = response,
             color = month)) +
  geom_point(size = 2, position = position_dodge2(width = 0.5)) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL),
                 position = position_dodge2(width = 0.5)) +
#  scale_color_manual(values = c(1,2,3,4,5, 1,4,2,3,5, 1,2,3,4,5)) +
  facet_grid(~ crop, scales = "free") +
  coord_flip() +
  labs(y = expression(paste("Biomass (g plant "^"-1",")")), x = NULL) +
  theme_test() +
  theme(legend.position = "bottom") 

ggsave("figures/combined2.png", width = 6)
```


```{r}
result %>% 
  filter(month == "First transplanting") %>% 
  group_by(month, crop) %>% 
  mutate(location = reorder_within(location, 
                                   by = response, 
                                   within = crop)) %>% 
  ggplot(aes(x = location, y = response,
             color = location)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL)) +
  scale_color_manual(values = c(1,2,4,3,5, 1,3,2,4,5, 1,2,4,3,5)) +
  facet_grid(crop ~ month, scales = "free") +
  coord_flip() +
  ylim(0, 30) +
  scale_x_reordered() +
  labs(y = expression(paste("Biomass (g plant "^"-1",")")), x = NULL) +
  theme_test() +
  theme(legend.position = "none") -> first

ggsave("figures/first.png", width = 3)
```

```{r}
theme_set(theme_test(base_family = "roboto"))
result %>% 
  filter(month == "Second transplanting") %>% 
  group_by(month, crop) %>% 
  mutate(location = reorder_within(location, 
                                   by = response, 
                                   within = crop)) %>% 
  ggplot(aes(x = location, y = response,
             color = location)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL)) +
  scale_color_manual(values = c(1,2,3,4,5, 1,4,2,3,5, 1,2,3,4,5)) +
  facet_grid(crop ~ month, scales = "free") +
  coord_flip() +
  ylim(0, 80) +
  scale_x_reordered() +
  labs(y = expression(paste("Biomass (g plant "^"-1",")")), x = NULL) +
  theme_test() +
  theme(legend.position = "none") -> second

ggsave("figures/second.png", width = 3)
```


```{r}
first | second

ggsave("figures/biomass.png", width = 6)
```





```{r}
biom %>%
  unite("crop_yr", c("crop", "year"), sep = "-") %>% 
  filter(!is.na(weight)) %>% 
  group_by(month) %>% 
  nest(-month) %>% 
  mutate(model = map(data, ~ lmer(log(biomass) ~ crop_yr + 
                                 (1|location), data = .x)),
         anova = map(model, anova),
         emmeans = map(model, ~ emmeans(., ~ crop_yr, 
                                        type = "response"))) -> analysis2
```


```{r}
#anova
analysis2$anova[[2]]
```

```{r}
analysis2$emmeans[[2]] %>% 
  as_tibble() %>% 
  mutate(month = "Second transplanting") -> second2

analysis2$emmeans[[1]] %>% 
  as_tibble() %>% 
  mutate(month = "First transplanting") %>% 
  bind_rows(second2) -> result2
```


```{r}
result2 %>% 
  filter(month == "First transplanting") %>% 
  ggplot(aes(x = crop_yr, y = response,
             color = crop_yr)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL)) +
  scale_color_manual(values = c(1,2,4,3,5, 1,3,2,4,5, 1,2,4,3,5)) +
  facet_grid(~ month, scales = "free") +
  coord_flip() +
  ylim(0, 30) +
  labs(y = expression(paste("Biomass (g plant "^"-1",")")), x = NULL) +
  theme_test() +
  theme(legend.position = "none") -> first

ggsave("figures/first_crop.png")
```

```{r}
theme_set(theme_test(base_family = "roboto"))
result2 %>% 
  filter(month == "Second transplanting") %>% 
  ggplot(aes(x = crop_yr, y = response,
             color = crop_yr)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL)) +
  scale_color_manual(values = c(1,2,3,4,5, 1,4,2,3,5, 1,2,3,4,5)) +
  facet_grid(~ month, scales = "free") +
  coord_flip() +
  ylim(0, 20) +
  labs(y = expression(paste("Biomass (g plant "^"-1",")")), x = NULL) +
  theme_test() +
  theme(legend.position = "none") -> second

ggsave("figures/second_crop.png")
```


```{r}
first | second

ggsave("figures/biomass.png", width = 6)
```



```{r}
biom %>% 
  ggplot(aes(x = crop, y = biomass, label = n)) +
  geom_jitter(alpha = 0.2) +
  geom_boxplot() +
  facet_grid(~month, scales = "free") +
  coord_flip()
```


```{r}
data1 %>% 
  ggplot(aes(x = crop, y = weight)) +
  geom_jitter(alpha = 0.2) +
  facet_grid(month ~ location) +
  coord_flip()
```








```{r}
options(scipen = 999)
library(ggstream)
library(ggridges)

data1 %>% 
  filter(!is.na(weight)) %>% 
  dplyr::select(month, crop, weight, doyh) %>% 
  group_by(month, crop) %>% 
  mutate(n = n()) %>% 
  mutate(rate = weight / n) %>% 
  group_by(month, crop, doyh) %>% 
  summarise(biomass = sum(rate)) %>% 
  mutate(doyh = as.integer(doyh)) -> biomass
```


```{r}
biomass %>% 
  ggplot(aes(x = doyh, y = biomass, fill = crop, label = crop)) +
  geom_stream(bw = 0.75, geom = "polygon", type = "ridge") +
#  geom_stream_label(size = 4, type = "proportional", n_grid = 1000) +
  facet_grid(~ month, scales = "free_x") +
  scale_fill_manual(values = c("#412234","#EE4B2B","#32CD32")) +
  labs(y = "Biomass (g plant)") +
  theme_test()

ggsave("figures/biomass.png")
```


```{r}
options(scipen = 999)
library(ggstream)
library(ggridges)

data1 %>% 
  filter(!is.na(height)) %>% 
  dplyr::select(month, crop, height, doyh) %>% 
  group_by(month, crop) %>% 
  mutate(n = n()) %>% 
  mutate(rate = height / n) %>% 
  group_by(month, crop, doyh) %>% 
  summarise(height = sum(rate)) %>% 
  mutate(doyh = as.integer(doyh)) -> height
```


```{r}
height %>% 
  ggplot(aes(x = doyh, y = height, fill = crop, label = crop)) +
  geom_stream(bw = 0.75, geom = "polygon", type = "proportional") +
  facet_grid(~ month, scales = "free_x") +
  geom_stream_label(size = 4, type = "proportional", n_grid = 1000) +
  scale_fill_manual(values = c("#412234","#EE4B2B","#32CD32")) +
  labs(y = "Height (g plant)") +
  theme_test()
```





