---
title: "Results"
author: "Maxwel Coura Oliveira"
date: "10/3/2019"
output: pdf_document
---

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(lme4)
library(lmerTest) 
library(emmeans)
library(ggpubr)
library(bestNormalize)
library(ggthemes)
library(nortest)
library(pbkrtest)
```

```{r include=FALSE}
data <- read_csv("Data.csv") %>% 
  drop_na(weight)
data$year <- factor(data$year)
glimpse(data)
```

```{r}
data %>% 
  summarise(max(doyh) - min(doyh))
```



```{r}
data %>% 
  group_by(crop, location, planting) %>% 
  summarise(mean = mean(weight), min = min(weight), max = max(weight)) %>% 
  ggplot(aes(x=planting, y=mean, fill = planting)) +
    geom_col() +
  facet_grid(location ~ crop) +
  coord_flip()
```


```{r}
data %>% 
  ggplot(aes(x = location, y = weight)) +
  geom_bar(stat="identity", fun.y = "mean") +
  facet_grid(planting ~ crop) +
  coord_flip()
```



```{r warning=FALSE}
data %>% 
#  filter(location == "clay center") %>% 
ggplot() + aes(x=doyh, y=weight, color=planting, size=height) + geom_jitter(alpha=0.5) +  facet_wrap(location~crop, ncol = 3, scales = "free_y") + theme_bw() + geom_smooth(method = "lm") +
  ggsave("biomass.pdf", height=18, width=9)
#  geom_vline(xintercept = 182, linetype="dotted", 
#                color = "blue", size=1.5)
```




# Testing Normality
```{r}
ggdensity(data$weight)
pearson.test(data$weight)
pearson.test(data$weight)
```

```{r}
ggdensity(log(data$weight))

pearson.test(log(data$weight))
pearson.test(data$weight) 
```

```{r}
databn <- bestNormalize(data$weight)
data$biomass <- databn$x.t
ggdensity(data$biomass)
```



```{r}
pearson.test(data$biomass)
pearson.test(data$biomass)
```


```{r}
ggplot(data, aes(x=crop, y=weight, color=crop)) + geom_jitter(alpha=0.4) +
  geom_boxplot() +
   coord_flip() + theme_bw() +
  facet_grid(year~planting~location) 
```



```{r warning=FALSE}
new_dt <- data %>% 
  filter(crop %in% "fallow",
         planting %in% "June") 
Model <- lmer(log(weight) ~ location + (1|year:location) + (1|plant:location), data= new_dt)
#summary(Model)
anova(Model)
```

```{r}

Model1 <- lmer(log(weight) ~ crop*planting + (1|year:plant), data=data)
```



```{r}
PBmodcomp(Model1, Model, nsim=500, cl=2) 
```


```{r}
anova(Model)
```

```{r}
?emmeans
```


```{r}
lsm <- emmeans(Model, ~  location ,  adjust="none", type="response")
lsm
```


```{r warning=FALSE}
cld <- CLD(lsm, adjust="none", Letters = letters, reversed = TRUE, type="response")
cld

#write_csv(cld, path="cld.csv")
```


```{r}
cld$location <- factor(cld$location, levels = c("grant", "clay center",  "havelock", "macomb",  "arlington"), labels=c("Grant, NE", "Clay Center, NE",  "Lincoln, NE", "Macomb, IL", "Arlington, WI"))

cld$crop <- factor(cld$crop, levels = c("corn", "soybean", "fallow"), labels=c("corn", "soybean", "fallow"))
cld$planting <- factor(cld$planting, levels =c("June", "July"), labels=c("June", "July"))
```



```{r}
ggplot(cld, aes(x=crop, y=response, color=crop, label=.group)) + 
  geom_point(size=3) + theme_bw() + labs(x="", y=expression(paste("Plamer amaranth (g plant"^"-1",")"))) +
  geom_errorbar(aes(ymin=lower.CL, ymax=upper.CL), width=0.1, size=1) +
  geom_text(nudge_y = c(100, 80, 80, 70, 40, 30, 200, 170, 100, 70, 60, 50, 260, 100, 100, 
                        100, 80, 50, 140, 100, 90, 50, 60, 50, 100, 80, 70, 70, 60, 60), size=6) +
  facet_grid(planting~location) + coord_flip() +
  scale_color_manual(values = c("blue", "darkgreen", "black", "orange", "red")) +
  theme(legend.position = "none", strip.text = element_text(size=18, face="bold"), axis.title = element_text(size=18),
        axis.text.x = element_text(size=17, angle = 45, hjust = 1), axis.text.y = element_text(size=17)) +
  ggsave("adaptation.png", height=8, width=20, dpi=600)
```




```{r}
data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) 
```




```{r}
arlington1 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "arlington" & planting == "June")

  chisq.test(arlington1$n)
  
  
  
arlington2 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "arlington" & planting == "July")

  chisq.test(arlington2$n) 
```





```{r}
macomb1 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "macomb" & planting == "June")

chisq.test(macomb1$n)
  
  
  
macomb2 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "macomb" & planting == "July")

chisq.test(macomb2$n) 
```

```{r}
havelock1 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "havelock" & planting == "June")

chisq.test(havelock1$n)
  
  
  
havelock2 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "havelock" & planting == "July")

chisq.test(havelock2$n) 
```

```{r}
clay1 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "clay center" & planting == "June")

chisq.test(clay1$n)
  
  
  
clay2 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "clay center" & planting == "July")

chisq.test(clay2$n) 
```



```{r}
grant1 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "grant" & planting == "June")

chisq.test(grant1$n)
  
  
  
grant2 <- data %>% 
  filter(!is.na(gender)) %>% 
  group_by(location, planting) %>% 
  count(gender, na.rm=TRUE) %>% 
  add_tally(name="nn") %>% 
  mutate(Perc=(n/nn)*100) %>% 
  filter(location == "grant" & planting == "July")

chisq.test(grant2$n)
```







```{r}
library(popbio)
?logi.hist.plot()
```


```{r}
data2 %>% 
  mutate(gender_A = case_when(
    gender == "m" ~ TRUE,
    gender == "f" ~ FALSE,
    TRUE ~ NA
  )) %>% 
  mutate_if(is_character, as.factor) %>% 
  filter(!is.na(gender_A)) %>% 
  mutate(doyh = as.numeric(doyh)) -> data3
```

```{r}
logi.hist.plot(data3$weight, data3$gender_A, 
               logi.mod = 1, boxp=FALSE, counts=FALSE, int= 10,
               type = "hist", rug = FALSE, col="gray")

ggsave("fig.png")
```


```{r}
aq.trans$survived <- aq.trans$fate!="dead"
a <- subset(aq.trans, leaf<50 & stage!="recruit", c(leaf,survived))
logi.hist.plot(a$leaf,  a$survived,
  type="hist", boxp=FALSE, counts=TRUE, int=10,
  ylabel="Survival probability", ylabel2="Number of plants",
  xlab="Number of leaves")
b <- glm(survived ~ leaf, binomial, data=a)
summary(b)
```



```{r}
data2 %>% 
  mutate(gender_A = case_when(
    gender == "m" ~ 0,
    gender == "f" ~ 1,
    TRUE ~ NA_real_
  )) %>% 
  mutate_if(is_character, as.factor) %>% 
  filter(!is.na(gender_A)) %>% 
  filter(!is.na(doyh)) %>% 
  filter(!is.na(weight)) %>% 
  filter(!is.na(height)) %>% 
  mutate(doyh = as.numeric(doyh)) -> data3
```

```{r}
seq(min(mtcars$hp), max(mtcars$hp),len=100)
```


```{r}
fit = glm(gender_A ~ doyh, data = data3, family=binomial)
newdat <- data.frame(doyh=seq(min(data3$doyh), max(data3$doyh), len=length(data3$doyh)))
newdat$vs = predict(fit, newdata=newdat, type="response")
plot(gender_A ~ doyh, data=data3, col="red4")
lines(gender_A ~ doyh, newdat, col="green4", lwd=2)
```





```{r}
label1 <- tibble(ed = "10% flowering", 
                   x = 2.35, y = 156.5, label = "June 01")
rect1 <- tibble(ed = "50% flowering", 
               x = 2.85, y = 195, xend = 2.7, yend = 199)

label2 <- tibble(ed = "10% flowering", 
                   x = 2.5, y = 186.5, label = "July 01")
rect2 <- tibble(ed = "50% flowering",  
               x = 3.05, y = 229, xend = 2.9, yend = 235)

month <- tibble(ed = "50% flowering",
                x = c(0.5, 0.5, 0.5, 0.5),
                y = c(168, 197, 228.5, 259), 
                label = c("June", "July", "August", "September"))

label3 <- tibble(ed = "50% flowering", 
                   x = 2.9, y = 240, label = "Second \ncohort")

label4 <- tibble(ed = "50% flowering", 
                   x = 2.7, y = 205, label = "First \ncohort")
```


```{r eval = FALSE, include=FALSE}
result3 %>% 
  mutate(ed = case_when(
    ed == "10" ~ "10% flowering",
    ed == "50" ~ "50% flowering",
    ed == "90" ~ "90% flowering",
    TRUE ~ "ed")) %>% 
  mutate(crop = fct_recode(crop,
          "<b style='color:#30123bFF;'>corn</b>" = "corn",
          "<b style='color:#fb832d;'>bareground</b>" = "bareground",
          "<b style='color:#28bbecff;'>soybean</b>" = "soybean")) %>% 
  ggplot(aes(x = crop, y = estimate)) +
  geom_segment(aes(x = 0.8, xend = 3.2, y = 153, yend = 153), 
             color = 1,
             alpha = 0.5) +
  geom_segment(aes(x = 0.8, xend = 3.2, y = 183, yend = 183), 
             color = 2,
             alpha = 0.5) +
  scale_x_discrete(expand = c(0.1, 0.1)) +
  geom_rect(mapping=aes(xmin= 0.8, xmax= 3.2,
                        ymin= 153, ymax= 183), 
            fill = "#FFFFF0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.8, xmax= 3.2,
                        ymin= 183, ymax= 214), 
            fill = "beige", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.8, xmax= 3.2,
                        ymin= 214, ymax= 244), 
            fill = "#F0FFF0", alpha=0.05) +
  geom_rect(mapping=aes(xmin= 0.8, xmax= 3.2,
                        ymin= 244, ymax= 274), 
            fill = "#F8F8FF", alpha=0.5) +
  geom_text(data = month, aes(x = x, y = y), label = month$label,
            size = 2, color = c("#8B8000", "#80461b", 
                                "darkgreen", "blue")) +
  scale_color_manual(values = c(1, 2)) +
  labs(x = NULL, y = "Day of year",
       title = NULL) +
  geom_curve(data = rect1, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             arrow = arrow(length = unit(0.07, "inch")), 
             color = 1,
             size = 0.4, curvature = 0.3) + 
  geom_curve(data = rect2, aes(x = x, y = y, 
                               xend = xend, yend = yend),
             color = 2,
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3) + 
  geom_text(data = label1, 
            aes(x = x, y = y), 
            size = 2, hjust = 0, angle = 270,
            label = label1$label, color = 1) +
  geom_text(data = label2, 
            aes(x = x, y = y), 
            size = 2, hjust = 0, angle = 270,
            label = label2$label, color = 2) +
  geom_text(data = label3, 
            aes(x = x, y = y), 
            size = 2, hjust = 0, 
            label = label3$label, color = 2) +
  geom_text(data = label4, 
            aes(x = x, y = y), 
            size = 2, hjust = 0, 
            label = label4$label, color = 1) +
  facet_grid(~ ed, scales = "free_y") +
  geom_point(aes(color = month), 
             size = 1,
             position = position_dodge2(width = 0.4)) +
  geom_linerange(aes(ymin = lower, ymax = upper, color = month), 
                 size = 1.3, position = position_dodge2(width = 0.4)) +
  coord_flip() +
  theme_test(base_family = "roboto") +
  theme(legend.position = "none",
        strip.text = element_markdown(face = "bold"),
        plot.title = element_markdown(),
        plot.title.position = "plot",
        axis.text.x = element_markdown(angle = 30),
        axis.text.y = element_markdown()) -> figure

#ggsave("figures/Combined1.png", width = 8, height = 4)
```

```{r eval = FALSE, include=FALSE}
(wrap_elements(full = curv1 | curv2)) / wrap_elements(full = figure) +
   plot_layout(heights = c(1.5, 1.5)) + plot_annotation(tag_levels = 'A')

#ggsave("figures/Combined2.png", height = 6)
```
